name: Build, Package, Release
on:
  release:
    types: [created]
  push:
    branches:
      - main
env:
  VERSION:

jobs:
  build-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Version to ENV
        run: |
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - id: containerRegistryLogin
        name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.MO_REGISTRY_AUTH_URL }}
          username: ${{ vars.MO_REGISTRY_USER }}
          password: ${{ secrets.MO_REGISTRY_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: ${{ vars.MO_DOCKERCONTEXT }}
          file: ${{ vars.MO_DOCKERFILE__MAIN }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ vars.MO_IMAGE_NAME }}:${{ env.VERSION }}
            ${{ vars.MO_IMAGE_NAME }}:latest    

      - id: releaseWithMogenius
        name: Release with mogenius
        uses: mogenius/mogenius-release-action@v1
        with:
          dev: true
          image: "${{ vars.MO_IMAGE_NAME }}:${{ env.VERSION }}"
          kind: ${{ vars.MO_KIND }}
          namespace: ${{ vars.MO_NAMESPACE_NAME }}
          resourceName: ${{ vars.MO_RESOURCE_NAME }}
          containerName: ${{ vars.MO_CONTAINER_NAME }}
          keyKind: ${{ vars.MO_API_KIND }}
          token: ${{ secrets.MO_API_TOKEN }}
